name: xml_parser 
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        #- name: Set up Python
        #uses: actions/setup-python@v2
        #with:
        #  python-version: '3.12'
        #- name: Install dependencies
        #run: pip install -r requirements.txt
          # - name: Run tests
          #  run: pytest --junitxml=reports/junit-report.xml
          # - run: npm ci
          # - run: npm test  
      - name: Process test report
        # e.g., a third-party action to parse JUnit XML and display a summary
        uses: dorny/test-reporter@v2
        with:
          name: 'Py Regression test results'
          path: 'build-*/*.xml'
          reporter: java-junit
